// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getTitleStmt, err = db.PrepareContext(ctx, getTitle); err != nil {
		return nil, fmt.Errorf("error preparing query GetTitle: %w", err)
	}
	if q.insertTitleStmt, err = db.PrepareContext(ctx, insertTitle); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTitle: %w", err)
	}
	if q.listPrincipalsForTitleStmt, err = db.PrepareContext(ctx, listPrincipalsForTitle); err != nil {
		return nil, fmt.Errorf("error preparing query ListPrincipalsForTitle: %w", err)
	}
	if q.upsertGenreStmt, err = db.PrepareContext(ctx, upsertGenre); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertGenre: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getTitleStmt != nil {
		if cerr := q.getTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTitleStmt: %w", cerr)
		}
	}
	if q.insertTitleStmt != nil {
		if cerr := q.insertTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTitleStmt: %w", cerr)
		}
	}
	if q.listPrincipalsForTitleStmt != nil {
		if cerr := q.listPrincipalsForTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPrincipalsForTitleStmt: %w", cerr)
		}
	}
	if q.upsertGenreStmt != nil {
		if cerr := q.upsertGenreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertGenreStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	getTitleStmt               *sql.Stmt
	insertTitleStmt            *sql.Stmt
	listPrincipalsForTitleStmt *sql.Stmt
	upsertGenreStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		getTitleStmt:               q.getTitleStmt,
		insertTitleStmt:            q.insertTitleStmt,
		listPrincipalsForTitleStmt: q.listPrincipalsForTitleStmt,
		upsertGenreStmt:            q.upsertGenreStmt,
	}
}
