// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Aka struct {
	TitleID         int64
	Ordering        int64
	Title           string
	Region          sql.NullInt64
	Language        sql.NullInt64
	Types           int64
	IsOriginalTitle int64
}

type AkasAttribute struct {
	ID   int64
	Name string
}

type AkasCarryAttribute struct {
	TitleID     int64
	Ordering    int64
	AttributeID int64
}

type AkasLanguage struct {
	ID   int64
	Name string
}

type AkasRegion struct {
	ID   int64
	Name string
}

type AkasType struct {
	ID   int64
	Name string
}

type BuildInfo struct {
	ID             int64
	CineVersion    string
	StartedAt      string
	FinishedAt     string
	FilterRated    int64
	FilterNotAdult int64
	HasPeople      int64
}

type BuildSource struct {
	File         string
	LastModified string
	Bytes        int64
	RowsRead     int64
}

type Episode struct {
	ID            int64
	ParentID      int64
	SeasonNumber  sql.NullInt64
	EpisodeNumber sql.NullInt64
}

type Name struct {
	ID          int64
	PrimaryName sql.NullString
	BirthYear   sql.NullInt64
	DeathYear   sql.NullInt64
}

type NamesKnownForTitle struct {
	NameID   int64
	Position int64
	TitleID  int64
}

type NamesPrimaryProfession struct {
	NameID       int64
	Position     int64
	ProfessionID int64
}

type NamesProfession struct {
	ID   int64
	Name string
}

type Principal struct {
	TitleID    int64
	Ordering   int64
	NameID     int64
	Category   int64
	Job        sql.NullInt64
	Characters sql.NullString
}

type PrincipalsCategory struct {
	ID   int64
	Name string
}

type PrincipalsJob struct {
	ID   int64
	Name string
}

type Title struct {
	ID             int64
	TitleType      int64
	PrimaryTitle   string
	OriginalTitle  sql.NullString
	IsAdult        int64
	StartYear      sql.NullInt64
	EndYear        sql.NullInt64
	RuntimeMinutes sql.NullInt64
	Genres         int64
	AverageRating  sql.NullInt64
	NumVotes       sql.NullInt64
}

type TitlesCreditName struct {
	TitleID  int64
	NameID   int64
	Role     int64
	Position int64
}

type TitlesGenre struct {
	ID   int64
	Name string
}

type TitlesType struct {
	ID   int64
	Name string
}
