// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getTitle = `-- name: GetTitle :one

SELECT id, title_type, primary_title, original_title, is_adult, start_year, end_year, runtime_minutes, genres, average_rating, num_votes FROM titles WHERE id = ? LIMIT 1
`

// Starter queries. The bulk-import hot path uses hand-written batched INSERTs
// (see the importer); these exercise codegen across the main table shapes.
func (q *Queries) GetTitle(ctx context.Context, id int64) (Title, error) {
	row := q.queryRow(ctx, q.getTitleStmt, getTitle, id)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.TitleType,
		&i.PrimaryTitle,
		&i.OriginalTitle,
		&i.IsAdult,
		&i.StartYear,
		&i.EndYear,
		&i.RuntimeMinutes,
		&i.Genres,
		&i.AverageRating,
		&i.NumVotes,
	)
	return i, err
}

const insertTitle = `-- name: InsertTitle :exec
INSERT INTO titles (
  id, title_type, primary_title, original_title, is_adult,
  start_year, end_year, runtime_minutes, genres, average_rating, num_votes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTitleParams struct {
	ID             int64
	TitleType      int64
	PrimaryTitle   string
	OriginalTitle  sql.NullString
	IsAdult        int64
	StartYear      sql.NullInt64
	EndYear        sql.NullInt64
	RuntimeMinutes sql.NullInt64
	Genres         int64
	AverageRating  sql.NullInt64
	NumVotes       sql.NullInt64
}

func (q *Queries) InsertTitle(ctx context.Context, arg InsertTitleParams) error {
	_, err := q.exec(ctx, q.insertTitleStmt, insertTitle,
		arg.ID,
		arg.TitleType,
		arg.PrimaryTitle,
		arg.OriginalTitle,
		arg.IsAdult,
		arg.StartYear,
		arg.EndYear,
		arg.RuntimeMinutes,
		arg.Genres,
		arg.AverageRating,
		arg.NumVotes,
	)
	return err
}

const listPrincipalsForTitle = `-- name: ListPrincipalsForTitle :many
SELECT title_id, ordering, name_id, category, job, characters FROM principals WHERE title_id = ? ORDER BY ordering
`

func (q *Queries) ListPrincipalsForTitle(ctx context.Context, titleID int64) ([]Principal, error) {
	rows, err := q.query(ctx, q.listPrincipalsForTitleStmt, listPrincipalsForTitle, titleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.TitleID,
			&i.Ordering,
			&i.NameID,
			&i.Category,
			&i.Job,
			&i.Characters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO titles_genre (id, name) VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name
RETURNING id
`

type UpsertGenreParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) (int64, error) {
	row := q.queryRow(ctx, q.upsertGenreStmt, upsertGenre, arg.ID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
