// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Hash struct {
	Hash  []byte
	Count int64
}

type Prefix struct {
	ID      int64
	Prefix  string
	Updated sql.NullInt64
	Etag    sql.NullString
}
