// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Prefix struct {
	ID      int64
	Prefix  string
	Updated sql.NullInt64
	Etag    sql.NullString
	Hashes  string
}
