// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deletePrefix = `-- name: DeletePrefix :exec
DELETE FROM prefixes WHERE id = ?
`

func (q *Queries) DeletePrefix(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePrefix, id)
	return err
}

const getEtags = `-- name: GetEtags :many
SELECT id, prefix, etag FROM prefixes
`

type GetEtagsRow struct {
	ID     int64
	Prefix string
	Etag   sql.NullString
}

func (q *Queries) GetEtags(ctx context.Context) ([]GetEtagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEtags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEtagsRow
	for rows.Next() {
		var i GetEtagsRow
		if err := rows.Scan(&i.ID, &i.Prefix, &i.Etag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrefix = `-- name: GetPrefix :one
SELECT id, prefix, updated, etag, hashes FROM prefixes WHERE prefix = ? LIMIT 1
`

func (q *Queries) GetPrefix(ctx context.Context, prefix string) (Prefix, error) {
	row := q.db.QueryRowContext(ctx, getPrefix, prefix)
	var i Prefix
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Updated,
		&i.Etag,
		&i.Hashes,
	)
	return i, err
}

const upsertPrefix = `-- name: UpsertPrefix :exec
INSERT INTO prefixes (prefix, updated, etag, hashes) VALUES (?, ?, ?, ?)
ON CONFLICT(prefix) DO UPDATE SET
  updated = excluded.updated,
  etag = excluded.etag,
  hashes = excluded.hashes
`

type UpsertPrefixParams struct {
	Prefix  string
	Updated sql.NullInt64
	Etag    sql.NullString
	Hashes  string
}

func (q *Queries) UpsertPrefix(ctx context.Context, arg UpsertPrefixParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrefix,
		arg.Prefix,
		arg.Updated,
		arg.Etag,
		arg.Hashes,
	)
	return err
}
