// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlite

import (
	"context"
)

const getHashCount = `-- name: GetHashCount :one
SELECT count FROM hashes WHERE hash = ?
`

func (q *Queries) GetHashCount(ctx context.Context, hash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHashCount, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const topPasswords = `-- name: TopPasswords :many
SELECT password, count FROM passwords ORDER BY count DESC LIMIT ?
`

func (q *Queries) TopPasswords(ctx context.Context, limit int64) ([]Password, error) {
	rows, err := q.db.QueryContext(ctx, topPasswords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Password
	for rows.Next() {
		var i Password
		if err := rows.Scan(&i.Password, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPassword = `-- name: UpsertPassword :exec
INSERT INTO passwords (password, count) VALUES (?, ?)
ON CONFLICT(password) DO UPDATE SET count = excluded.count
`

type UpsertPasswordParams struct {
	Password string
	Count    int64
}

func (q *Queries) UpsertPassword(ctx context.Context, arg UpsertPasswordParams) error {
	_, err := q.db.ExecContext(ctx, upsertPassword, arg.Password, arg.Count)
	return err
}
