// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const deleteHashRange = `-- name: DeleteHashRange :exec
DELETE FROM hashes WHERE hash BETWEEN ?1 AND ?2
`

type DeleteHashRangeParams struct {
	Lower []byte
	Upper []byte
}

func (q *Queries) DeleteHashRange(ctx context.Context, arg DeleteHashRangeParams) error {
	_, err := q.exec(ctx, q.deleteHashRangeStmt, deleteHashRange, arg.Lower, arg.Upper)
	return err
}

const deletePrefix = `-- name: DeletePrefix :exec
DELETE FROM prefixes WHERE id = ?
`

func (q *Queries) DeletePrefix(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deletePrefixStmt, deletePrefix, id)
	return err
}

const getEtags = `-- name: GetEtags :many
SELECT id, prefix, etag FROM prefixes
`

type GetEtagsRow struct {
	ID     int64
	Prefix string
	Etag   sql.NullString
}

func (q *Queries) GetEtags(ctx context.Context) ([]GetEtagsRow, error) {
	rows, err := q.query(ctx, q.getEtagsStmt, getEtags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEtagsRow
	for rows.Next() {
		var i GetEtagsRow
		if err := rows.Scan(&i.ID, &i.Prefix, &i.Etag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHashCount = `-- name: GetHashCount :one
SELECT count FROM hashes WHERE hash = ?
`

func (q *Queries) GetHashCount(ctx context.Context, hash []byte) (int64, error) {
	row := q.queryRow(ctx, q.getHashCountStmt, getHashCount, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPrefix = `-- name: GetPrefix :one
SELECT id, prefix, updated, etag FROM prefixes WHERE prefix = ? LIMIT 1
`

func (q *Queries) GetPrefix(ctx context.Context, prefix string) (Prefix, error) {
	row := q.queryRow(ctx, q.getPrefixStmt, getPrefix, prefix)
	var i Prefix
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Updated,
		&i.Etag,
	)
	return i, err
}

const insertHash = `-- name: InsertHash :exec
INSERT INTO hashes (hash, count) VALUES (?, ?)
`

type InsertHashParams struct {
	Hash  []byte
	Count int64
}

func (q *Queries) InsertHash(ctx context.Context, arg InsertHashParams) error {
	_, err := q.exec(ctx, q.insertHashStmt, insertHash, arg.Hash, arg.Count)
	return err
}

const upsertPrefix = `-- name: UpsertPrefix :exec
INSERT INTO prefixes (prefix, updated, etag) VALUES (?, ?, ?)
ON CONFLICT(prefix) DO UPDATE SET
  updated = excluded.updated,
  etag = excluded.etag
`

type UpsertPrefixParams struct {
	Prefix  string
	Updated sql.NullInt64
	Etag    sql.NullString
}

func (q *Queries) UpsertPrefix(ctx context.Context, arg UpsertPrefixParams) error {
	_, err := q.exec(ctx, q.upsertPrefixStmt, upsertPrefix, arg.Prefix, arg.Updated, arg.Etag)
	return err
}
