// Package loremipsum generates "lorem ipsum" Latin placeholder text.
//
// It is a faithful port of Django's django/utils/lorem_ipsum.py, differing only
// in that each function takes an explicit *rand.Rand so callers control the
// random stream and can produce reproducible output.
package loremipsum

import (
	"math/rand/v2"
	"strings"
)

// CommonP is the standard "lorem ipsum" opening paragraph.
const CommonP = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod " +
	"tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim " +
	"veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea " +
	"commodo consequat. Duis aute irure dolor in reprehenderit in voluptate " +
	"velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint " +
	"occaecat cupidatat non proident, sunt in culpa qui officia deserunt " +
	"mollit anim id est laborum."

// words is the pool of Latin words drawn on for random text.
var words = []string{
	"exercitationem", "perferendis", "perspiciatis", "laborum", "eveniet",
	"sunt", "iure", "nam", "nobis", "eum", "cum", "officiis", "excepturi",
	"odio", "consectetur", "quasi", "aut", "quisquam", "vel", "eligendi",
	"itaque", "non", "odit", "tempore", "quaerat", "dignissimos", "facilis",
	"neque", "nihil", "expedita", "vitae", "vero", "ipsum", "nisi", "animi",
	"cumque", "pariatur", "velit", "modi", "natus", "iusto", "eaque", "sequi",
	"illo", "sed", "ex", "et", "voluptatibus", "tempora", "veritatis", "ratione",
	"assumenda", "incidunt", "nostrum", "placeat", "aliquid", "fuga", "provident",
	"praesentium", "rem", "necessitatibus", "suscipit", "adipisci", "quidem",
	"possimus", "voluptas", "debitis", "sint", "accusantium", "unde", "sapiente",
	"voluptate", "qui", "aspernatur", "laudantium", "soluta", "amet", "quo",
	"aliquam", "saepe", "culpa", "libero", "ipsa", "dicta", "reiciendis",
	"nesciunt", "doloribus", "autem", "impedit", "minima", "maiores",
	"repudiandae", "ipsam", "obcaecati", "ullam", "enim", "totam", "delectus",
	"ducimus", "quis", "voluptates", "dolores", "molestiae", "harum", "dolorem",
	"quia", "voluptatem", "molestias", "magni", "distinctio", "omnis", "illum",
	"dolorum", "voluptatum", "ea", "quas", "quam", "corporis", "quae",
	"blanditiis", "atque", "deserunt", "laboriosam", "earum", "consequuntur",
	"hic", "cupiditate", "quibusdam", "accusamus", "ut", "rerum", "error",
	"minus", "eius", "ab", "ad", "nemo", "fugit", "officia", "at", "in", "id",
	"quos", "reprehenderit", "numquam", "iste", "fugiat", "sit", "inventore",
	"beatae", "repellendus", "magnam", "recusandae", "quod", "explicabo",
	"doloremque", "aperiam", "consequatur", "asperiores", "commodi", "optio",
	"dolor", "labore", "temporibus", "repellat", "veniam", "architecto", "est",
	"esse", "mollitia", "nulla", "a", "similique", "eos", "alias", "dolore",
	"tenetur", "deleniti", "porro", "facere", "maxime", "corrupti",
}

// commonWords are the opening words of the standard "lorem ipsum" text.
var commonWords = []string{
	"lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipisicing",
	"elit", "sed", "do", "eiusmod", "tempor", "incididunt", "ut", "labore",
	"et", "dolore", "magna", "aliqua",
}

// Sentence returns a randomly generated sentence of lorem ipsum text.
//
// The first word is capitalised and the sentence ends in either a period or
// question mark. Commas are added at random.
func Sentence(rng *rand.Rand) string {
	sections := make([]string, between(rng, 1, 5))
	for i := range sections {
		sections[i] = strings.Join(sample(rng, words, between(rng, 3, 12)), " ")
	}
	s := strings.Join(sections, ", ")
	return strings.ToUpper(s[:1]) + s[1:] + choice(rng, "?.")
}

// Paragraph returns a randomly generated paragraph of lorem ipsum text.
//
// The paragraph consists of between 1 and 4 sentences, inclusive.
func Paragraph(rng *rand.Rand) string {
	sentences := make([]string, between(rng, 1, 4))
	for i := range sentences {
		sentences[i] = Sentence(rng)
	}
	return strings.Join(sentences, " ")
}

// Paragraphs returns count paragraphs as generated by Paragraph.
//
// If common is true then the first paragraph is the standard "lorem ipsum"
// paragraph. Otherwise the first paragraph is random Latin text. Either way,
// subsequent paragraphs are random Latin text.
func Paragraphs(rng *rand.Rand, count int, common bool) []string {
	paragraphs := make([]string, 0, count)
	for i := range count {
		if common && i == 0 {
			paragraphs = append(paragraphs, CommonP)
		} else {
			paragraphs = append(paragraphs, Paragraph(rng))
		}
	}
	return paragraphs
}

// Words returns count lorem ipsum words separated by a single space.
//
// If common is true then the first 19 words are the standard "lorem ipsum"
// words. Otherwise all words are selected randomly.
func Words(rng *rand.Rand, count int, common bool) string {
	var wordList []string
	if common {
		wordList = append(wordList, commonWords...)
	}

	available := len(wordList)
	if count > available {
		count -= available
		for count > 0 {
			chunk := min(count, len(words))
			count -= chunk
			wordList = append(wordList, sample(rng, words, chunk)...)
		}
	} else {
		wordList = wordList[:count]
	}
	return strings.Join(wordList, " ")
}

// sample returns count distinct words drawn uniformly from pool.
//
// It uses a partial Fisher-Yates shuffle over an index slice, mirroring
// Python's random.sample (selection without replacement).
func sample(rng *rand.Rand, pool []string, count int) []string {
	indices := make([]int, len(pool))
	for i := range indices {
		indices[i] = i
	}
	out := make([]string, count)
	for i := range count {
		j := i + rng.IntN(len(indices)-i)
		indices[i], indices[j] = indices[j], indices[i]
		out[i] = pool[indices[i]]
	}
	return out
}

// between returns a random integer in the inclusive range [low, high].
func between(rng *rand.Rand, low, high int) int {
	return low + rng.IntN(high-low+1)
}

// choice returns a single randomly chosen byte from options as a string.
func choice(rng *rand.Rand, options string) string {
	return string(options[rng.IntN(len(options))])
}
