AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-lambda

  Bare-bones example running Go code under AWS Lambda

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x

    Properties:
      CodeUri: hello/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
      - x86_64

      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
